/**
 * OpsPanel — Phase Ops-Monitor-B: Read-only operations diagnostics panel.
 *
 * Safety guarantees:
 * - Read-only GET requests only
 * - Never triggers /api/generate, cleanup, deletion, reset, or restart
 * - Never exposes raw IPs, sourceHashes, prompts, API keys, tokens, raw logs,
 *   or absolute filesystem paths
 */

import { useState, useEffect, useCallback, useRef } from 'react';
import type { HealthInfo } from '../../lib/serverApi';
import styles from './OpsPanel.module.css';

const REFRESH_INTERVAL_MS = 30_000;
const PUBLIC_URL = 'https://music.conanxin.com';
const GITHUB_REPO = 'https://github.com/conanxin/mmx-music-studio';
const CURRENT_RELEASE = 'v0.4.16-alpha';

// ── Types ──────────────────────────────────────────────────────────────────────

interface RuntimeStatus {
  ok: boolean;
  service?: string;
  timestamp?: string;
  runtimeStatus?: {
    backend?: { current?: string; realGenerationEnabled?: boolean; mockGenerationEnabled?: boolean };
    launchGuard?: {
      enabled?: boolean;
      publicGenerationEnabled?: boolean;
      perSourceDailyLimit?: number;
      generationCooldownSeconds?: number;
    };
    jobQueue?: {
      enabled?: boolean;
      pending?: number;
      running?: number;
      succeeded?: number;
      failed?: number;
    };
    storage?: {
      trackCount?: number;
      audioFileCount?: number;
      approxAudioBytes?: number;
      readable?: boolean;
    };
  };
}

interface OpsData {
  health: HealthInfo | null;
  status: RuntimeStatus | null;
  fetchedAt: Date | null;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function formatBytes(bytes: number): string {
  if (!bytes) return '0 B';
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  if (bytes < 1024 * 1024 * 1024) return `${(bytes / 1024 / 1024).toFixed(2)} MB`;
  return `${(bytes / 1024 / 1024 / 1024).toFixed(2)} GB`;
}

function buildDiagnosticSummary(health: HealthInfo | null, status: RuntimeStatus | null): string {
  const rs = status?.runtimeStatus;
  const guard = rs?.launchGuard;
  const queue = rs?.jobQueue;
  const storage = rs?.storage;
  const backend = rs?.backend;

  const lines = [
    'MMX Music Studio Ops Summary',
    `Release: ${CURRENT_RELEASE}`,
    `Public URL: ${PUBLIC_URL}`,
    `Timestamp: ${status?.timestamp ?? new Date().toISOString()}`,
    '',
    '## Service',
    `  ok: ${health?.ok ?? status?.ok ?? false}`,
    `  backend: ${backend?.current ?? health?.backend ?? 'unknown'}`,
    `  realGenerationEnabled: ${backend?.realGenerationEnabled ?? health?.realGenerationEnabled ?? false}`,
    `  mockGenerationEnabled: ${backend?.mockGenerationEnabled ?? health?.mockGenerationEnabled ?? false}`,
    '',
    '## Launch Guard',
    `  enabled: ${guard?.enabled ?? health?.launchGuardEnabled ?? false}`,
    `  publicGenerationEnabled: ${guard?.publicGenerationEnabled ?? health?.publicGenerationEnabled ?? false}`,
    `  perSourceDailyLimit: ${guard?.perSourceDailyLimit ?? health?.perSourceDailyLimit ?? 'N/A'}`,
    `  generationCooldownSeconds: ${guard?.generationCooldownSeconds ?? health?.generationCooldownSeconds ?? 'N/A'}`,
    '',
    '## Job Queue',
    `  enabled: ${queue?.enabled ?? health?.jobQueueEnabled ?? false}`,
    `  pending: ${queue?.pending ?? health?.queuedJobs ?? 0}`,
    `  running: ${queue?.running ?? 0}`,
    `  succeeded: ${queue?.succeeded ?? 0}`,
    `  failed: ${queue?.failed ?? 0}`,
    '',
    '## Storage',
    `  trackCount: ${storage?.trackCount ?? 0}`,
    `  audioFileCount: ${storage?.audioFileCount ?? 0}`,
    `  approxAudioBytes: ${storage?.approxAudioBytes ?? 0} (${formatBytes(storage?.approxAudioBytes ?? 0)})`,
    `  readable: ${storage?.readable ?? false}`,
    '',
    '---',
    'Generated by mmx-music-studio Ops Panel (read-only)',
  ];

  return lines.join('\n');
}

// ── Sub-components ────────────────────────────────────────────────────────────

function StatusBadge({ ok, label }: { ok: boolean | undefined; label: string }) {
  const active = ok === true;
  return (
    <span className={`${styles.badge} ${active ? styles.badgeOk : styles.badgeError}`}>
      <span className={styles.badgeDot} />
      {label}
    </span>
  );
}

function GuardBadge({ enabled }: { enabled: boolean | undefined }) {
  return (
    <span className={`${styles.badge} ${enabled ? styles.badgeOk : styles.badgeWarn}`}>
      <span className={styles.badgeDot} />
      {enabled ? '开启' : '关闭'}
    </span>
  );
}

function PublicGenBadge({ enabled }: { enabled: boolean | undefined }) {
  return (
    <span className={`${styles.badge} ${enabled ? styles.badgeOk : styles.badgeWarn}`}>
      <span className={styles.badgeDot} />
      {enabled ? '已开启' : '已暂停'}
    </span>
  );
}

// ── Main component ────────────────────────────────────────────────────────────

export default function OpsPanel() {
  const [data, setData] = useState<OpsData>({ health: null, status: null, fetchedAt: null });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const mountedRef = useRef(true);

  const fetchData = useCallback(async () => {
    if (!mountedRef.current) return;
    setLoading(prev => data.health === null && data.status === null ? true : prev);
    setError(null);

    try {
      const [healthRes, statusRes] = await Promise.all([
        fetch('/api/health'),
        fetch('/api/status'),
      ]);

      if (!mountedRef.current) return;

      const [health, status]: [HealthInfo, RuntimeStatus] = await Promise.all([
        healthRes.ok ? healthRes.json() : Promise.resolve({} as HealthInfo),
        statusRes.ok ? statusRes.json() : Promise.resolve({} as RuntimeStatus),
      ]);

      if (!mountedRef.current) return;

      const fetchedAt = new Date();
      setData({ health, status, fetchedAt });
      setLoading(false);
    } catch (err) {
      if (!mountedRef.current) return;
      setError(err instanceof Error ? err.message : '获取数据失败');
      setLoading(false);
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // Initial fetch + auto-refresh
  useEffect(() => {
    mountedRef.current = true;
    fetchData();
    const interval = setInterval(fetchData, REFRESH_INTERVAL_MS);
    return () => {
      mountedRef.current = false;
      clearInterval(interval);
    };
  }, [fetchData]);

  const health = data.health;
  const rs = data.status?.runtimeStatus;
  const guard = rs?.launchGuard;
  const queue = rs?.jobQueue;
  const storage = rs?.storage;
  const backend = rs?.backend;

  const summary = buildDiagnosticSummary(health, data.status);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(summary);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // clipboard not available
    }
  };

  // Error state
  if (error && !health && !data.status) {
    return (
      <div className={styles.page}>
        <div className={styles.header}>
          <h1 className={styles.title}>运维诊断</h1>
          <p className={styles.subtitle}>Public Alpha Runtime Diagnostics</p>
        </div>
        <div className={styles.errorCard}>
          <div className={styles.errorTitle}>无法获取运维数据</div>
          <div className={styles.errorMsg}>{error}</div>
          <button className={styles.retryBtn} onClick={fetchData}>
            重试
          </button>
        </div>
      </div>
    );
  }

  const lastUpdated = data.fetchedAt
    ? `上次刷新：${data.fetchedAt.toLocaleTimeString('zh-CN')}`
    : '正在加载…';

  return (
    <div className={styles.page}>
      {/* Header */}
      <div className={styles.header}>
        <div className={styles.titleRow}>
          <h1 className={styles.title}>运维诊断</h1>
          {loading && <div className={styles.refreshSpinner} />}
        </div>
        <p className={styles.subtitle}>Public Alpha Runtime Diagnostics — 只读，不触发生成或清理</p>
        <div className={styles.refreshRow}>
          <button className={styles.refreshBtn} onClick={fetchData} disabled={loading}>
            {loading ? '刷新中…' : '刷新'}
          </button>
          <span className={styles.lastUpdated}>{lastUpdated}</span>
        </div>
      </div>

      {/* Read-only notice */}
      <div className={styles.notice}>
        此页面为只读运维诊断面板，不会触发任何生成、清理、删除、重启或重置操作。
        不会暴露 IP 地址、API Key、Token、Prompt 或日志内容。
      </div>

      {/* Service status grid */}
      <div className={styles.grid}>
        {/* Service card */}
        <div className={styles.card}>
          <h2 className={styles.cardTitle}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/>
            </svg>
            服务状态
          </h2>
          <div className={styles.statusRows}>
            <div className={styles.statusRow}>
              <span className={styles.statusLabel}>健康检查</span>
              <StatusBadge ok={health?.ok ?? data.status?.ok} label="正常" />
            </div>
            <div className={styles.statusRow}>
              <span className={styles.statusLabel}>Public URL</span>
              <span className={styles.statusValue}>
                <a href={PUBLIC_URL} className={styles.versionLink} target="_blank" rel="noopener noreferrer">
                  {PUBLIC_URL}
                </a>
              </span>
            </div>
            <div className={styles.statusRow}>
              <span className={styles.statusLabel}>Backend</span>
              <span className={styles.statusValue}>{backend?.current ?? health?.backend ?? '—'}</span>
            </div>
            <div className={styles.statusRow}>
              <span className={styles.statusLabel}>真实生成</span>
              <span className={styles.statusValue}>
                <StatusBadge ok={backend?.realGenerationEnabled ?? health?.realGenerationEnabled} label={backend?.realGenerationEnabled ?? health?.realGenerationEnabled ? '可用' : '禁用'} />
              </span>
            </div>
            <div className={styles.statusRow}>
              <span className={styles.statusLabel}>模拟模式</span>
              <span className={styles.statusValue}>
                <StatusBadge ok={backend?.mockGenerationEnabled ?? health?.mockGenerationEnabled} label={backend?.mockGenerationEnabled ?? health?.mockGenerationEnabled ? '启用' : '禁用'} />
              </span>
            </div>
          </div>
        </div>

        {/* Launch Guard card */}
        <div className={styles.card}>
          <h2 className={styles.cardTitle}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
            </svg>
            生成入口保护
          </h2>
          <div className={styles.statusRows}>
            <div className={styles.statusRow}>
              <span className={styles.statusLabel}>Guard 启用</span>
              <span className={styles.statusValue}>
                <GuardBadge enabled={guard?.enabled ?? health?.launchGuardEnabled} />
              </span>
            </div>
            <div className={styles.statusRow}>
              <span className={styles.statusLabel}>公开生成</span>
              <span className={styles.statusValue}>
                <PublicGenBadge enabled={guard?.publicGenerationEnabled ?? health?.publicGenerationEnabled} />
              </span>
            </div>
            <div className={styles.statusRow}>
              <span className={styles.statusLabel}>每来源日限额</span>
              <span className={styles.statusValue}>
                {guard?.perSourceDailyLimit ?? health?.perSourceDailyLimit ?? '—'} 次/天
              </span>
            </div>
            <div className={styles.statusRow}>
              <span className={styles.statusLabel}>冷却时间</span>
              <span className={styles.statusValue}>
                {guard?.generationCooldownSeconds ?? health?.generationCooldownSeconds ?? '—'} 秒
              </span>
            </div>
            <div className={styles.statusRow}>
              <span className={styles.statusLabel}>说明</span>
              <span className={styles.statusValue} style={{ fontSize: '0.8rem', color: 'var(--color-text-secondary)' }}>
                {guard?.publicGenerationEnabled ?? health?.publicGenerationEnabled
                  ? '生成已开启'
                  : '生成已暂停，Library 和播放器仍可使用'}
              </span>
            </div>
          </div>
        </div>

        {/* Job Queue card */}
        <div className={styles.card}>
          <h2 className={styles.cardTitle}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/>
              <line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/>
              <line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/>
            </svg>
            任务队列
          </h2>
          <div className={styles.queueGrid}>
            <div className={`${styles.queueStat} ${styles.queueStatPending}`}>
              <span className={styles.queueStatValue}>{queue?.pending ?? health?.queuedJobs ?? 0}</span>
              <span className={styles.queueStatLabel}>排队中</span>
            </div>
            <div className={`${styles.queueStat} ${styles.queueStatRunning}`}>
              <span className={styles.queueStatValue}>{queue?.running ?? 0}</span>
              <span className={styles.queueStatLabel}>运行中</span>
            </div>
            <div className={`${styles.queueStat} ${styles.queueStatSucceeded}`}>
              <span className={styles.queueStatValue}>{queue?.succeeded ?? 0}</span>
              <span className={styles.queueStatLabel}>成功</span>
            </div>
            <div className={`${styles.queueStat} ${styles.queueStatFailed}`}>
              <span className={styles.queueStatValue}>{queue?.failed ?? 0}</span>
              <span className={styles.queueStatLabel}>失败</span>
            </div>
          </div>
          {(queue?.running ?? 0) > 0 && (
            <div className={styles.statusRow}>
              <span className={styles.statusLabel}>状态</span>
              <span className={`${styles.badge} ${styles.badgeWarn}`}>
                <span className={styles.badgeDot} />有任务运行中
              </span>
            </div>
          )}
          {(queue?.failed ?? 0) > 0 && (
            <div className={styles.statusRow}>
              <span className={styles.statusLabel}>状态</span>
              <span className={`${styles.badge} ${styles.badgeError}`}>
                <span className={styles.badgeDot} />存在失败任务
              </span>
            </div>
          )}
        </div>

        {/* Storage card */}
        <div className={styles.card}>
          <h2 className={styles.cardTitle}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <ellipse cx="12" cy="5" rx="9" ry="3"/>
              <path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"/>
              <path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"/>
            </svg>
            存储概览
          </h2>
          <div className={styles.storageBar}>
            <span className={styles.storageSize}>
              {formatBytes(storage?.approxAudioBytes ?? 0)}
            </span>
            <div className={styles.storageMeta}>
              <span className={styles.storageMetaItem}>
                曲目：{storage?.trackCount ?? 0}
              </span>
              <span className={styles.storageMetaItem}>
                音频：{storage?.audioFileCount ?? 0}
              </span>
            </div>
            {(storage?.trackCount ?? 0) !== (storage?.audioFileCount ?? 0) && (
              <span className={`${styles.badge} ${styles.badgeWarn}`}>
                <span className={styles.badgeDot} />数量不一致
              </span>
            )}
            {storage?.readable === false && (
              <span className={`${styles.badge} ${styles.badgeError}`}>
                <span className={styles.badgeDot} />存储不可读
              </span>
            )}
          </div>
        </div>

        {/* Version & Release card */}
        <div className={styles.card}>
          <h2 className={styles.cardTitle}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M20 7H4a2 2 0 00-2 2v6a2 2 0 002 2h16a2 2 0 002-2V9a2 2 0 00-2-2z"/>
              <polyline points="16 3 12 7 8 3"/>
            </svg>
            版本与发布
          </h2>
          <div className={styles.statusRows}>
            <div className={styles.statusRow}>
              <span className={styles.statusLabel}>当前版本</span>
              <span className={styles.statusValue}>{CURRENT_RELEASE}</span>
            </div>
            <div className={styles.statusRow}>
              <span className={styles.statusLabel}>定位</span>
              <span className={styles.statusValue} style={{ fontSize: '0.8rem', color: 'var(--color-text-secondary)' }}>
                Storage management dry-run
              </span>
            </div>
          </div>
          <div className={styles.versionLinks}>
            <a href={GITHUB_REPO} className={styles.versionLink} target="_blank" rel="noopener noreferrer">
              GitHub Repo →
            </a>
            <a href={`${GITHUB_REPO}/releases`} className={styles.versionLink} target="_blank" rel="noopener noreferrer">
              Releases →
            </a>
            <a href={`${GITHUB_REPO}/actions`} className={styles.versionLink} target="_blank" rel="noopener noreferrer">
              GitHub Actions →
            </a>
          </div>
        </div>
      </div>

      {/* Diagnostic Summary */}
      <div className={styles.summaryCard}>
        <h2 className={styles.summaryCardTitle}>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/>
            <polyline points="14 2 14 8 20 8"/>
            <line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/>
          </svg>
          诊断摘要
        </h2>
        <pre className={styles.summaryPre}>{summary}</pre>
        <div className={styles.summaryActions}>
          <button
            className={`${styles.copyBtn} ${copied ? styles.copyBtnCopied : ''}`}
            onClick={handleCopy}
          >
            {copied ? (
              <>
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <polyline points="20 6 9 17 4 12"/>
                </svg>
                已复制
              </>
            ) : (
              <>
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <rect x="9" y="9" width="13" height="13" rx="2" ry="2"/>
                  <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/>
                </svg>
                复制诊断摘要
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
